#! /bin/sh

#bspc config border_width         2
bspc config window_gap          15
bspc config top_padding		20
#bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
#bspc config history_aware_focus  true
bspc config focus_follows_pointer false
# bspc config pointer_follows_focus true
bspc config remove_disabled_monitor true
bspc config remove_unlugged_monitor true
bspc config merge_overlapping_monitors true
bspc config click_to_focus true
#bspc monitor -d '\uf001' '\u190' '\u169' '\u169' '\u29'
# bspc monitor -d MUSIC GAMES VIDEO BROWSER TERMINUS
xrandr | grep 'DisplayPort-0 connected' > /dev/null && \
    ( bspc monitor eDP -d HipChat Secondary ; bspc monitor DisplayPort-0 -d E-mail Monitoring Project ) || \
        bspc monitor eDP -d HipChat Secondary Tertiary
# bspc monitor HDMI-0 -d E-mail Monitoring Project
# bspc monitor -d     

bspc rule -a Firefox desktop=^4
bspc rule -a MPlayer desktop=^3 follow=on focus=on state=fullscreen
bspc rule -a HipChat desktop=^1 follow=on focus=on
bspc rule -a URxvt:Secondary desktop=^2 follow=off focus=off
