#! /bin/sh

#bspc config border_width         2
bspc config window_gap          15
bspc config top_padding		20
#bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

#bspc monitor -d '\uf001' '\u190' '\u169' '\u169' '\u29'
bspc monitor -d MUSIC GAMES VIDEO BROWSER TERMINAL 

bspc rule -a Firefox desktop=^4
bspc rule -a MPlayer desktop=^3 follow=on focus=on state=fullscreen

